version: '3'
services:
  bot:
    build: .
    command: npm install pm2 -g && npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - API_KEY=5818810312:AAFmP5gobbXbsWkOSilZJhDuJk7J_ElPyWE
